# Generated by Django 4.0.3 on 2022-04-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('bankcode', models.IntegerField(max_length=10)),
                ('fee', models.IntegerField(max_length=10)),
                ('remittor', models.CharField(max_length=30)),
                ('recipient', models.CharField(max_length=30)),
                ('account_no', models.IntegerField(max_length=50)),
                ('bank_name', models.CharField(max_length=10)),
                ('user_id', models.IntegerField()),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sends',
            },
        ),
    ]
