# Generated by Django 4.0.3 on 2022-04-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanagementservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='account_no',
            field=models.IntegerField(),
        ),
    ]
