# Generated by Django 4.0.3 on 2022-04-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanagementservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send',
            name='memo',
        ),
    ]
