# Generated by Django 4.0.3 on 2022-04-15 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanagementservice', '0002_remove_send_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_detail', to='cashmanagementservice.send')),
            ],
            options={
                'db_table': 'send_detail',
            },
        ),
    ]
