# Generated by Django 4.0.3 on 2022-04-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanagementservice', '0002_alter_send_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='bankcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='send',
            name='fee',
            field=models.IntegerField(),
        ),
    ]
