# Generated by Django 4.0.3 on 2022-04-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanagementservice', '0003_send_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_detail',
            name='memo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
