# Generated by Django 4.0.3 on 2022-04-11 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashmanagementservice', '0003_alter_send_bankcode_alter_send_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
