# Generated by Django 4.0.3 on 2022-04-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanagementservice', '0004_alter_send_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='account_no',
            field=models.CharField(max_length=50),
        ),
    ]
