# Generated by Django 4.0.3 on 2022-04-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanagementservice', '0005_alter_send_account_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='send',
            old_name='user_id',
            new_name='user',
        ),
    ]
