# Generated by Django 4.0.3 on 2022-04-12 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashmanagementservice', '0006_rename_user_id_send_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='account_no',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='send',
            name='bank_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='send',
            name='recipient',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='send',
            name='remittor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='send',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
