# Generated by Django 4.0.3 on 2022-04-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanagementservice', '0008_alter_send_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='fee',
            field=models.IntegerField(default=500),
        ),
    ]
